spring:
#  config:
#    activate:
#      on-profile: embedded

  activemq:
    packages:
      trust-all: true

logging:
  level:
    org.apache.activemq: INFO
    org.apache.springframework: DEBUG

---
spring:
  profiles:
    active: embedded